[tool.poetry]
name = "hardi-edtech"
version = "0.1.0"
description = ""
authors = ["h0s0r <hardidar.ldh@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.50.0"
langchain = "^0.3.27"
langchain-community = "^0.3.31"
ollama = "^0.6.0"
tavily-python = "^0.7.12"
chromadb = "^1.1.1"
pypdf = "^6.1.1"
sentence-transformers = "^5.1.1"
python-dotenv = "^1.1.1"
wikipedia = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"